variable "region" {}
variable "gcp_project" {}
variable "credentials" {}
variable "name" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "gce_ssh_user" {}
variable "gce_ssh_pub_key_file" {}
variable "public_key" {}
